name: audioplayers_example
description: Demonstrates how to use the audioplayers plugin.

dependencies:
  flutter:
    sdk: flutter
  audioplayers:
    path: ../
  http: ^0.12.2
  path_provider: ^1.6.28
  path_provider_macos: ^0.0.4+8
  provider: 4.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/audio.mp3
    - assets/audio2.mp3
    - assets/messenger.mp3
    - assets/file_example_OOG_5MG.ogg

environment:
  sdk: ">=2.7.0 <3.0.0"
